### PR TITLE
Checklist: Account for Scale in Image Resolution Check

### LINKED ISSUE #9439: Checklist: Image Resolution Check Should Consider Scale
Currently the PPC check for image resolution isn't considering scale, it should. 

Follow up from #9401.

### PR DESCRIPTION
**Pull request by maxyinger**
## Context
Part of image resolution check in checklist.

## Summary
Accounts for element scale when performing image resolution check in the checklist.

## Relevant Technical Choices
NA

## To-do
NA

## User-facing changes
Now if your image is scaled really large and the uploaded resolution is less than it, it should populate the images scaling recommendation in the checklist.

## Testing Instructions
This is pretty hard to verify by interacting with the UI, so I'm gonna say it doesn't need QA verification. let me know if you think otherwise.

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. upload an image with a resolution that at a scale of 1 would be less that 2x element size, but at a scale of 4x, wouldn't
2. scale the image up all the way and see that this check passes.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9439

### CODE REVIEW

**Review by samwhale — APPROVED** [review]
tested and it works well. Wondering if we should update the text shown as well. The issue card doesn't suggest decreasing the scaling:

**Comment by maxyinger** [comment]
I can add something like:
> Consider scaling down the image

But that may be confusing cus you want to scale down the image element inside the editor, not the image you upload to the editor.

but wondering if that's kinda covered by:
> Consider similar pixel density for cropped images

idk. open to whatever here

**Comment by samwhale** [comment]
> I can add something like:
> 
> > Consider scaling down the image
> 
> But that may be confusing cus you want to scale down the image element inside the editor, not the image you upload to the editor.
> 
> but wondering if that's kinda covered by:
> 
> > Consider similar pixel density for cropped images
> 
> idk. open to whatever here

To me it feels like it should point to setting the scale since that's a possible solution, so maybe the first one? I think the second one implies it but what if you don't understand pixel density 🤷

**Comment by BrittanyIRL** [comment]
> > I can add something like:
> > > Consider scaling down the image
> > 
> > 
> > But that may be confusing cus you want to scale down the image element inside the editor, not the image you upload to the editor.
> > but wondering if that's kinda covered by:
> > > Consider similar pixel density for cropped images
> > 
> > 
> > idk. open to whatever here
> 
> To me it feels like it should point to setting the scale since that's a possible solution, so maybe the first one? I think the second one implies it but what if you don't understand pixel density 🤷

i have this in a PR right now, lemme know what you think: https://github.com/google/web-stories-wp/pull/9440

**Review by BrittanyIRL — APPROVED** [review]
Works for me!

**Comment by maxyinger** [comment]
> i have this in a PR right now, lemme know what you think: #9440

Oh nice! that looks good to me

**Pull request merged**
