### PR TITLE
Custom Fonts: Enable by default

### LINKED ISSUE #10925: Custom Fonts: Enable by default
## Task Description

Let's enable both relevant feature flags ahead of the release

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

Enable custom fonts for 1.19

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:
#### Add / remove font
0. Go to dashboard > Settings.
0. Add a custom font. Eg [overpass-extrabold-italic.ttf](https://overpass-30e2.kxcdn.com/overpass-extrabold-italic.ttf)
0. See font to added.
0. Delete font.
0. See font removed. 

#### Add a duplicate font
0. Go to dashboard > Settings.
0. Add a custom font. Eg [overpass-extrabold-italic.ttf](https://overpass-30e2.kxcdn.com/overpass-extrabold-italic.ttf)
0. See font to added.
0. Add some font again. 
0. See error message. 

#### Permission error, delete font. 

1. Login as admin.
1. Go setting panel.
1. Open another window.
1. To WordPress CMS.
1. Logout.
1. To back to original window.
1. Try to delete font.
1. See error message. 

Try above, but only using keyboard navigation to tab between inputs

Once font is added. 
3. Create new story. 
4. A text element. 
5. Change font to new custom font. 
6. See font preview work. 
7. Publish story. 
8. View story. 
9. See text element and font render correctly. 

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10925

### CODE REVIEW

**Comment by swissspidy** [comment]
This is blocked by #10996 and #11050.

Afterwards, let's add some QA instructions to get a final review on this.

**Review by swissspidy — APPROVED** [review]
QA instructions would be beneficial, just to triple check this feature.

**Comment by swissspidy** [comment]
@spacedmonkey Can you add QA instructions here? Once #11070 is merged it would be great to test this again from A-Z since there have been plenty of changes recently.

Thanks in advance!

**Comment by spacedmonkey** [comment]
> Can you add QA instructions here? 

@swissspidy Done!

**Pull request merged**
